project:
  type: website
  output-dir: docs

website:
  title: "Programming notes"
  site-url: https://olavlan.github.io/
  description: "My notes about programming"
  navbar:
    right:
      - icon: github
        href: https://github.com/olavlan/olavlan.github.io

execute: 
  echo: true
  output: false
  freeze: true

code-fold: true
code-overflow: wrap
code-copy: true
highlight-style: mocha.theme

bibliography: references.bib

page-layout: full


format:
  html:
    code-fold: true
    theme:
      - superhero
