project:
  type: book
  output-dir: docs

book:
  title: "Programming notes"
  author: "Olav Landsverk"
  date: "2/20/2026"
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - part: Pydantic AI
      chapters:
        - chapters/pydantic-ai/first/agent.ipynb

execute: 
  echo: true
  output: false
  freeze: true

code-fold: true
code-overflow: wrap
code-copy: true
highlight-style: mocha.theme

bibliography: references.bib

page-layout: full


format:
  html:
    theme:
      - superhero
