project:
  type: book

book:
  title: "Personal notes"
  author: "Olav Landsverk"
  date: "2/20/2026"
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - part: My part
      chapters:
        - chapters/test.qmd

execute: 
  freeze: true

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
