project:
  type: book

book:
  title: "Programming notes"
  author: "Olav Landsverk"
  date: "2/20/2026"
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - part: Pydantic AI
      chapters:
        - chapters/pydantic-ai/naive/agent.ipynb

execute: 
  echo: true
  output: false
  freeze: true

highlight-style: mocha.theme

code-fold: true
code-overflow: wrap
code-copy: true

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
